import {
  BarChart3,
  BatteryCharging,
  BrainCircuit,
  Briefcase,
  Bug,
  Calendar,
  Car,
  CheckCircle,
  ClipboardCheck,
  Cpu,
  Factory,
  FileText,
  Filter,
  Headphones,
  Landmark,
  Link2,
  Lock,
  Megaphone,
  Network,
  RefreshCw,
  Search,
  LineChart,
  Target,
  Mail,
  Share2,
  Ticket,
  TrendingUp,
  Truck,
  Tv,
  Users,
  UserPlus,
  UtensilsCrossed,
  Smartphone,
  Settings,
  MapPin,
  ShoppingCart,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Layout,
  Server,
  Layers,
  Monitor,
  Code,
  PenTool,
  Palette,
  Video,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const serviceIcons = {
  barChart3: BarChart3,
  batteryCharging: BatteryCharging,
  brainCircuit: BrainCircuit,
  briefcase: Briefcase,
  bug: Bug,
  calendar: Calendar,
  car: Car,
  checkCircle: CheckCircle,
  clipboardCheck: ClipboardCheck,
  cpu: Cpu,
  factory: Factory,
  fileText: FileText,
  filter: Filter,
  headphones: Headphones,
  landmark: Landmark,
  link2: Link2,
  lock: Lock,
  megaphone: Megaphone,
  network: Network,
  refreshCw: RefreshCw,
  search: Search,
  lineChart: LineChart,
  target: Target,
  mail: Mail,
  share2: Share2,
  ticket: Ticket,
  trendUp: TrendingUp,
  truck: Truck,
  tv: Tv,
  users: Users,
  userPlus: UserPlus,
  utensilsCrossed: UtensilsCrossed,
  smartphone: Smartphone,
  settings: Settings,
  mapPin: MapPin,
  shoppingCart: ShoppingCart,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldAlert: ShieldAlert,
  layout: Layout,
  server: Server,
  layers: Layers,
  monitor: Monitor,
  code: Code,
  penTool: PenTool,
  palette: Palette,
  video: Video,
  wifi: Wifi,
  wrench: Wrench,
} as const;

export type ServiceIconName = keyof typeof serviceIcons;

export function getServiceIcon(name: ServiceIconName): LucideIcon {
  return serviceIcons[name];
}
